### ISSUE TITLE
Difference with AMASS-Annotation-Unifier? 

### ISSUE THREAD

**Issue by EvenGu** [LinghaoChan/UniMoCap#1]
Hi, thank you for your good work. I wonder what is the main difference between your work and the AMASS-Annotation-Unifier? 
In addition, are you going to include the Motion-X dataset?

**Comment by LinghaoChan** [comment]
@EvenGu 

Thanks for your interest. When I tried to run the code of AMASS-Annotation-Unifier, I found that part of the humanact12 in HumanML3D has some bugs. Please see the detailed issue I raised there. Based on some codebase of it, I set up this project. I detailed the copyright in each file. For UniMoCap, an open-source project, we not only support the body-only format but whole-body as well, which can be easily merged with Motion-X with the tomato data format. 

Any question? Let me know.

**Comment by EvenGu** [comment]
Thank you for your prompt reply. That makes sense.
Two more questions: 
1) I thought in HumanML3D, their process includes data augmentation ( both motion files and the text description). However, in your **Body-only data preprocessing** doc, it seems that you mirrored it again? Or am I missing something here?
2) Does the text for Babel also include tokens like /NOUN, /DET, ... as in the text files in HumanML3D?

 Thanks.

**Comment by LinghaoChan** [comment]
@EvenGu Thanks for further discussion. For mirroring, this is conducted because BABEL and KIT are not mirrored. If we mirrored the H3D twice, it would not have a negative effect. For the 2nd question, in my ablation, these tokens are useless. As a result, they are not included in UniMoCap.

**Comment by LinghaoChan** [comment]
Are there any more questions?

**Comment by LinghaoChan** [comment]
Close it. If any problem, reopen it or raise another.
