### ISSUE TITLE
As a novice, do I need to further updates of the repo, or am I able to start learning motion from this repo?

### ISSUE THREAD

**Issue by hdjsjyl** [LinghaoChan/UniMoCap#2]
Hi Authro,
     Thanks for your excellent work. As a novice for 3D motion, is it a good start from this repo for learning?
     Any advice would be appreciated. thank you!

**Comment by LinghaoChan** [comment]
@hdjsjyl Thanks for your interest. 

This is a project to unify existing text2motion datasets. You will know more about the data and have a better understanding of motion datasets. This is very essential to your research and engineering.

**Comment by hdjsjyl** [comment]
Hi @LinghaoChan , really appreciate your reply. Will look at the details of this repo. Thanks

**Comment by LinghaoChan** [comment]
Due to workflows on other projects, I did not update this project recently. Maybe there are some small bugs, feel free to raise them as issues. And I will resolve them accordingly.

**Comment by hdjsjyl** [comment]
Yes, will do, thank you.

**Comment by LinghaoChan** [comment]
Close it. If any problem, reopen it or raise another.
